# Generated by Django 4.0.6 on 2022-10-19 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BackEndApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('CNIC', models.CharField(max_length=13)),
                ('fName', models.CharField(max_length=30)),
                ('lName', models.CharField(max_length=30)),
                ('license_No', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('address', models.CharField(max_length=999, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, default='profile.jpg', null=True, upload_to='doctor_profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
